config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'page#home'
  get 'show'              => 'users#show'
  get 'edit/:id'          => 'users#edit'
  get 'new'               => 'accounts#new'

  resources :accounts
  resources :page
  resources :users

end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user
  validates :title, presence: true
  validates :identifier, presence: true
  validates :identifier, length: { is: 16 }
  validates :identifier, uniqueness: true
  
  before_validation :generate_identifier

  def initialize(attributes = {})
    super
    self.identifier = generate_identifier
  end

  def self.identifiers
    all.map{ |account| account.identifier }
  end
  
  def generate_identifier
    identifiers = self.class.identifiers
    gen_id = rand.to_s[2..17]
    while identifiers.include? gen_id
      gen_id = rand.to_s[2..17]
    end
    gen_id
  end

end

app/models/litigation.rb
class Litigation < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :accounts
  validates :email, uniqueness: true

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

def new
@account = Account.new
end

def create
@account = Account.new(account_params)
  if @account.save
    flash[:notice] = "Votre compte a bien été ajouté"
    redirect_to user_path(@account.id)
  else
    flash[:error] = "Il semble qu'il y ait une erreur dans votre saisie."
    render :new
  end
end

private
def account_params
params.require(:account).permit(:title, :user_id)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
     @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

def show
  @user = current_user
  @masculin = @user.is_female == false
  @accounts = current_user.accounts
end

def edit
  @user = User.find(params[:id])
end

def update
   @user = User.find(params[:id])
  if @user.update(user_params)  
    flash[:notice] = "Votre compte à été mis à jour"
    redirect_to user_path(@user.id)
  else
    flash[:alert] = "Il y a eu une erreur, merci de recommencer..."
    render :edit
  end
end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :is_female)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/new.html.erb
<h1>Nouveau compte</h1>

<p>Entrez le libellé de votre nouveau compte, un identifiant lui sera automatiquement attribué.</p>

<%=form_for (@account) do |f|%>
  <%=f.label :Libellé%>
  <%=f.text_field :title%>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit "Submit"  %> 
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Ma banque | <%=yield(:title).empty? ? "Bienvenue" : yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://yegor256.github.io/tacit/tacit.min.css"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
</head>

<header>
<div class="row">
  <div class="col-md-12">
    <%= link_to "/" do %>
      <img class= "logo" src= "http://amazone54.a.m.pic.centerblog.net/0_a9e44_2c0da8aa_L.png"/>
    <%end%>

    <p class="navbar-text pull-right nav">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Paramètres de connexion', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% if current_user.admin? %>
        | <%= link_to "Admin", rails_admin_path%>
      <%end%>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
     <% end %>
    </p>
  </div>
</div>
</header>

<body>



  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/page/home.html.erb
<h1>Bienvenue sur votre banque en ligne</h1>

<% if user_signed_in? %>
  <%=link_to "Mon compte", user_path(@user)%>
<%else%>
  <p>Merci de vous identifier pour accéder aux services en ligne</p>
<%end%>

app/views/users/edit.html.erb
<h1>Editer mon profil</h1>

<%= form_for (@user) do |f|%>
  <div class="field">
    <%= f.label :Nom %><br />
    <%= f.text_field :last_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :Prénom %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :Adresse %><br />
    <%= f.text_field :address, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :Sexe %><br />
    <%= f.select :is_female, [["Masculin", false], ["Féminin", true]] %>
  </div>
 <%= f.submit "Submit"  %> 
 <% end %>

app/views/users/show.html.erb
<%=provide(:title, "Mon compte")%>

<h1>Mon profil</h1>
  <% if @user.first_name.nil? && @user.last_name.nil? && @user.address.nil? %>
    <p>Merci de compléter votre profil <%= link_to "Go !", edit_user_path(current_user.id) %></p>
  <%else%>
    <p><%= @user.try(:last_name)%></br>
    <%= @user.try(:first_name)%></br>
      <%if @user.try(:@masculin) %>
        Masculin</br>
      <%else%>
        Féminin</br>
      <%end%>
    <%=link_to "Modifier mes informations", edit_user_path(current_user.id)%>

  <%end%>
<%= @user.try(:address)%></br></p>

<hr>

<h2>Mes comptes</h2>

<div>
  <ul>
  <% @accounts.each do |account| %>
    <li><%= account.try(:title) %></br>
        <%= account.try(:identifier) %></li> 
  <%end%>
  </ul>
</div>


<%=link_to "Créer un nouveau compte", new_path %>